name: Dart Release

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Fetch current files
        run: wget https://github.com/sirily11/disney-queue/releases/latest/download/disney.csv -P data
      - name: Run application
        run: dart bin/main.dart
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./data/disney.csv
