name: Dart Release

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt -y install wget
      - name: Install dependencies
        run: pub get
      - name: Fetch current files
        run: wget https://github.com/sirily11/disney-queue/releases/latest/download/disney.csv -P data
      - name: Run application
        run: dart bin/main.dart
      - name: Github Release create, update, and upload assets
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          tag: master
          files: |
            data/disney.csv
