name: Dart Release

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run application
        run: dart bin/main.dart
        env:
          apiBackend: ${{secrets.ENDPOINT}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
      - name: Upload to database
        run: pipenv run python upload.py
        working-directory: './scripts'

