name: Dart Release

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        run: apt-get install software-properties-common
      - run: add-apt-repository ppa:deadsnakes/ppa
      - run: apt-get update
      - run: apt -y install python3.8
      - name: Install dependencies
        run: pub get
      - name: Run application
        run: dart bin/main.dart
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install python dependencies
        run: pipenv install
        working-directory: "./scripts"
      - name: Upload to database
        run: pipenv run python upload.py
        working-directory: './scripts'
        env:
          endpoint: ${{secrets.ENDPOINT}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}